# Generated by Django 3.2 on 2022-08-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.CharField(max_length=200, verbose_name='Imagen')),
            ],
            options={
                'db_table': 'platos',
            },
        ),
    ]
